apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-review-mcp
spec:
  rules:
    - host: mcp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-review-mcp
                port:
                  number: 80
