apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secrets
  namespace: ai-review
type: Opaque
stringData:
  AZURE_OPENAI_ENDPOINT: "https://openai-prod-eastus-yogi0001122.openai.azure.com/"
  AZURE_OPENAI_KEY: "11GyfYJwaMzYgh0KuJEvyMzEvXSZML7QDH8VnKIgjXR5u6HkDmg7JQQJ99BJACYeBjFXJ3w3AAABACOG5rkz"
